name = "dongle-japes"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

# Your actual Cloudflare account ID
account_id = "d06947482eaa23c05c503a12f796bed7"

# Static site configuration
[site]
bucket = "./build"

# Environment variables (replace with your actual values)
[vars]
DISCORD_BOT_TOKEN = "YOUR_DISCORD_BOT_TOKEN"
DISCORD_SERVER_ID = "YOUR_DISCORD_SERVER_ID"
SPOTIFY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"

# Production environment
[env.production]
name = "dongle-japes-prod"
route = "donglejapes.com/*"

[env.production.vars]
DISCORD_BOT_TOKEN = "YOUR_DISCORD_BOT_TOKEN"
DISCORD_SERVER_ID = "YOUR_DISCORD_SERVER_ID"
SPOTIFY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"

# KV namespaces for data storage (optional)
# [[kv_namespaces]]
# binding = "DONGLE_DATA"
# id = "YOUR_KV_NAMESPACE_ID"
# preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"